database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/clevertec
  username: postgres
  password: root
liquibase:
  changelog_path: classpath:db/changelog/changelog.yml
  should_run: false